### PR TITLE
pypandoc 1.3.3

### PR DESCRIPTION
**Pull request by janschulz**

### CODE REVIEW

**Comment by janschulz** [comment]
@conda-forge-manager @conda-forge-status any idea why it fails?

```
MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
  curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
  
  export PATH=/Users/travis/miniconda3/bin:$PATH
  
  conda config --set show_channel_urls true
  conda update --yes conda
  conda install --yes conda-build=1.20.0 jinja2 anaconda-client
  conda config --add channels conda-forge
  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/Users/travis/build.sh: line 52: conda: command not found
/Users/travis/build.sh: line 53: conda: command not found
/Users/travis/build.sh: line 54: conda: command not found
/Users/travis/build.sh: line 55: conda: command not found
The command "MINICONDA_URL="http://repo.continuum.io/miniconda"
  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
  curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
  
  export PATH=/Users/travis/miniconda3/bin:$PATH
  
  conda config --set show_channel_urls true
  conda update --yes conda
  conda install --yes conda-build=1.20.0 jinja2 anaconda-client
  conda config --add channels conda-forge
  " failed and exited with 127 during .
```

**Comment by ocefpaf** [comment]
@janschulz latest conda-smithy should fix this. But it looks like you are having trouble on Windows (https://github.com/conda-forge/conda-smithy/issues/350). Until we figure out a solution I can send a rerender PR for you here from my Linux machine. Hold on.

**Comment by janschulz** [comment]
If it's a `conda smithy regenerate`: I can't currently do that, as I'm on windows and run into https://github.com/conda-forge/conda-smithy/issues/350

**Comment by janschulz** [comment]
@ocefpaf Thanks!

**Comment by janschulz** [comment]
Just went through the conda-smithy commits and this seemed like an obvious try :-)

**Comment by janschulz** [comment]
I added that manually, still no regenerate

**Comment by janschulz** [comment]
Handled in https://github.com/conda-forge/pypandoc-feedstock/pull/4

**Pull request closed without merging**
